[package]
name = "day-05"
version = "0.1.0"
authors = ["Juan Navarro <juan.navarro@gmx.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
