[package]
name = "day-13"
version = "0.1.0"
authors = ["Juan Navarro <juan.navarro@gmx.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.9.1"
num-traits = "0.2"
num-derive = "0.3"
